services:
  backend:
    build:
      context: .  # Pfad zum Ordner, wo das Backend dockerfile liegt
      dockerfile: dockerfile.backend
    container_name: conduit_backend
    ports:
      - ${SERVER_PORT_BACKEND:-8000}:${CONTAINER_PORT_BACKEND:-8000}
    env_file:
      - .env
    volumes:
      - backend_data:/app/data
    restart: always
    networks:
      - conduit_net


  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    container_name: conduit_frontend
    ports:
      - ${SERVER_PORT_FRONTEND:-8282}:${CONTAINER_PORT_FRONTEND:-80}
    env_file:
      - .env
    depends_on:
      - backend
    restart: always
    networks:
      - conduit_net


volumes:
  backend_data:

networks:
  conduit_net:
    driver: bridge